### ISSUE TITLE
openOCD can not configures the related "Width of System Bus Access" (sbcs.sbaccess) by return value of sbcs.sbacccess128/64/32/16/8 ?

### ISSUE THREAD

**Issue by Qidi-ic** [riscv/riscv-openocd#1177]
cfg file has add system bus access option:
`riscv set_mem_access sysbus`

source code also shows how openOCD handle the sbcs.sbaccess field:
https://github.com/riscv-collab/riscv-openocd/blob/ca8092015716dbc9ae69dd8240197b00b5900b0a/src/target/riscv/riscv-013.c#L2349

However, this function is called by others in context. I'm not sure whether openOCD will modify sbcs.sbaccess according to sbaccess8/16/32/64 in sbcs to achieve access with different bit widths. 

Moreover, I also noticed that "size_bytes" finally is called by this:
https://github.com/riscv-collab/riscv-openocd/blob/ca8092015716dbc9ae69dd8240197b00b5900b0a/src/target/riscv/riscv-013.c#L1245

**Comment by en-sc** [comment]
@Qidi-ic, I didn't quite get what your question is.

Memory access requests in OpenOCD specify  the width of the access.

If the requested access width is not supported by System Bus (i.e. the corresponding `sbcs.sbaccess` bit is low) the access will fail.

**Comment by Qidi-ic** [comment]
> If the requested access width is not supported by System Bus (i.e. the corresponding `sbcs.sbaccess` bit is low) the access will fail.

Really thanks for your reply, @en-sc ! 

Surely,  the width of System Bus access depends on `sbcs.sbaccess` in hardware. I've also noticed that `sbcs.sbaccess8/16/32/64/128` (Preset) fields indicate the access width supported by the current hardware.  I'm wondering whether openOCD will configure the width of Memory access based on `sbcs.sbaccess8/16/32/64/128` ? 

e.g. 
`sbcs.sbaccess8 = 1'b1`
`sbcs.sbaccess16 = 1'b1`
`sbcs.sbaccess32 = 1'b1`
`sbcs.sbaccess64 = 1'b0`
`sbcs.sbaccess128 = 1'b0`

When a new Memory access is requested, which access width is configured in the `sbcs,sbaccess` by openOCD?

**Comment by en-sc** [comment]
> When a new Memory access is requested, which access width is configured in the sbcs,sbaccess by openOCD?

When a user requests a memory access via TCL interface, they specify the width they want to use for this access.
E.g.:
* `read/write_memory` commands have the `width` argument:
  https://openocd.org/doc/html/General-Commands.html#Target-State-handling
* `md*`/`mw*` commands specify the width in the name of the command:
  https://openocd.org/doc/html/General-Commands.html#index-memory-access


However, GDB's packets do not specify the access width (https://sourceware.org/gdb/current/onlinedocs/gdb.html/Packets.html#Packets), and OpenOCD is free to choose the access width.

Currently RISC-V targets use the default implementation that first aligns the access and then accesses the memory using `riscv013_data_bits`-wide accesses:
https://github.com/riscv-collab/riscv-openocd/blob/ea8f9d51954b979ff6b4d90afa70352763199b63/src/target/target.c#L2437-L2471

https://github.com/riscv-collab/riscv-openocd/blob/ea8f9d51954b979ff6b4d90afa70352763199b63/src/target/riscv/riscv-013.c#L2118-L2152

There is definitely room for improvement there, e.g. on a target that supports only 32-bit wide unaligned System Bus Access, current algorithm will fail to write a memory region that does is not aligned, since it will attempt to align the start address using accesses with smaller sizes.

**Comment by Qidi-ic** [comment]
Very appreciate for such a detailed answer!

I now have a clearer understanding of the SBA access mechanism. 

Furthermore, over the past few days, I've been trying to use GDB to try to configure 64bit access on a platform that supports up to 32 bits. OpenOCD  would initiate 2 time 32-bit accesses to complete 64-bit System Bus Access request by calling this code:


https://github.com/riscv-collab/riscv-openocd/blob/ea8f9d51954b979ff6b4d90afa70352763199b63/src/target/riscv/riscv.c#L1393C1-L1423C2

This function is not easy to found in debugging process, this may be that this mechanism is not explicitly stated in the User Guide. By the way, the aim of this issue is to find out the System Bus Access width configuration in openOCD. It seems to be solved! 

Thanks!

**Comment by en-sc** [comment]
Closing this one. Created #1184 to track the work on improving `target->type->read/write_buffer`.
