### ISSUE TITLE
How to quit GDB without interrupt running program

### ISSUE THREAD

**Issue by Kendidi** [riscv/riscv-openocd#610]
Hi all,

I use OpenOCD and GDB to load and run application on RISCV32 core-0.  How can I let the application continue to run, and quit/exit GDB and then disconnected OpenOCD?

The reason is after I start running application on core 0, I want to connect to core 1 and do the same.  Please advise!  Thanks a lot in advance!

**Comment by TommyMurphyTM1234** [comment]
In the OpenOCD debug script add a gdb-detach event handler and call resume?
________________________________
From: Kendidi ***@***.***>
Sent: Wednesday, May 19, 2021 3:48:10 AM
To: riscv/riscv-openocd ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [riscv/riscv-openocd] How to quit GDB without interrupt running program (#610)


Hi all,

I use OpenOCD and GDB to load and run application on RISCV32 core-0. How can I let the application continue to run, and quit/exit GDB and then disconnected OpenOCD?

The reason is after I start running application on core 0, I want to connect to core 1 and do the same. Please advise! Thanks a lot in advance!

**Comment by timsifive** [comment]
I'd suggest leaving gdb running, and simply connect a second one. (Note that for that you don't want to use `-rtos auto` so that each hart shows up as its own core, and OpenOCD will listen on a second port for a second gdb.)

**Comment by Kendidi** [comment]
Thanks Tim for your advice! I will try. 

Best Regards
Kenneth Wong
