### ISSUE TITLE
riscv 0.11 debug not able to do flash programming

### ISSUE THREAD

**Issue by fanghuaqi** [riscv/riscv-openocd#757]
As commit  64f3f8877e9dbedf7b80ea3d544e5a6a5b17ed61 do,  

~~~c
	LOG_DEBUG("resume at 0x%" TARGET_PRIxADDR, entry_point);
	if (riscv_resume(target, 0, entry_point, 0, 1, true) != ERROR_OK)
		return ERROR_FAIL;
~~~

it might cause riscv 0.11 can't do flash programing, which I met as follows.

![image](https://user-images.githubusercontent.com/1538922/198922979-ba5dacd7-8b01-453e-9110-cbb7339fef6b.png)

we can solve it by change `0, 1` to `0, 0`, but not sure it will make any bad influnce on openocd other features, could you help check it.

Thanks

**Comment by timsifive** [comment]
I don't have time to dig into it in detail this week. I think #679 was right, and riscv-011 needs to be updated. The update is probably really trivial. As a first step, I'd try to remove the debug_execution check on line 1200 of riscv-011.c. There's nothing really special that happens when debug_execution is true.

**Comment by fanghuaqi** [comment]
Thanks @timsifive , we checked that removing the debug_execution check works, not sure whether it will affect other features in riscv 0.11 version debug.
